name: "Hello Actions"
description: "Greet myself"
author: "77384412+CyberCitizen01@users.noreply.github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "blue"
